spring:
  application:
    name: profile-service
  datasource:
    username: newroot
    password: root
    url: jdbc:mysql://localhost:3306/profiledb
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 0
  error:
    include-message: always
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
      serviceUrl:
        defaultZone: http://localhost:8762/eureka
customProperty:
  test: PavanKumar
management:
  endpoints:
    web:
      exposure:
        include: refresh, health
api:
  user: http://USER-SERVICE/user
